version: version 2.1
jobs:
  compile:
    docker:
     -image: xyzuan/xdocker:latest
   environment:
     LLVM_NAME:
       from_secret: LLVM_NAME
     TG_TOKEN:
       from_secret: TG_TOKEN
     TG_CHAT_ID:
       from_secret: TG_CHAT_ID
     GH_USERNAME:
       from_secret: GH_USERNAME
     GH_EMAIL:
       from_secret: GH_EMAIL
     GH_TOKEN:
       from_secret: GH_TOKEN
     GH_PUSH_REPO_URL:
       from_secret: GH_PUSH_REPO_URL
   commands:
     - bash llvm-tc_build.sh
